version : '3.3'
services:
  
  # OT Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.52.0
    command: ["--config=/otel-config.yaml"]
    environment: 
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - HONEYCOMB_TRACING_DATASET=${HONEYCOMB_TRACING_DATASET}
      - HONEYCOMB_METRICS_DATASET=${HONEYCOMB_METRICS_DATASET}
    volumes:
      - type: bind
        source: ${PWD}/otel-local-config.yaml
        target: /otel-config.yaml
        read_only: true
    ports:
      - "4317:4317"   # OTEL receiver

  otlp-log-receiver:
    build: .
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - HONEYCOMB_DATASET=${HONEYCOMB_TRACING_DATASET}
    depends_on:
      - otel-collector
    ports:
      - "8080:8080"   # OTEL Logs receiver